version: '3.8'

services:
  backend:
    build: ./backend
    container_name: backend
    ports:
      - "3000:3000"  # local 3000 → container 5000
    environment:
      - MONGO_URL=mongodb://mongo:27017/laundrydb
    depends_on:
      - mongo
    networks:
      - app-network

  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "8080:80" # local 8080 → container 80 (React built via nginx)
    depends_on:
      - backend
    networks:
      - app-network

  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mongo_data:
